/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Adsorb: typeof import('./src/components/Adsorb.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Moveable: typeof import('./src/components/Moveable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Tree: typeof import('./src/components/Tree.vue')['default']
  }
}
